name: Build and release package

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            dist
            package.json
            package-lock.json
            CHANGELOG.md
            LICENSE
            README.md

  release:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package
      - uses: volta-cli/action@v4
        with:
          registry-url: https://registry.npmjs.org
      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2
      - uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
